import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopMenu from '@/components/TopMenu'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Boss Massage App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TopMenu/>
        {children}
      </body>
    </html>
  )
}
